"specimen","bone","sex","age","side_of_body","plane_of_picture","orientation","picture_number","logic_tag"
"Arctocephalus pusillus_1","rib","-","-","-","coronal","-",500130,1
"Arctocephalus pusillus_1","rib","-","-","-","coronal","-",634983,2
"Arctocephalus pusillus_1","mandible","-","-","left","midsagittal","interior",245385,3
"Arctocephalus pusillus_1","mandible","-","-","left","midsagittal","exterior",929642,4
"Arctocephalus pusillus_1","vertebrae","-","-","-","coronal","anterior",956598,5
"Arctocephalus pusillus_1","vertebrae","-","-","-","coronal","posterior",770727,6
"Arctocephalus pusillus_2","phalange (2)","-","-","-","transverse","dorsal & ventral",855953,7
"Arctocephalus pusillus_2","phalange (2)","-","-","-","midsagittal","sides",263833,8
"Arctocephalus pusillus_3_box","skull","female","adult","-","transverse","dorsal",370173,9
"Arctocephalus pusillus_3_box","skull","female","adult","-","transverse","ventral",673815,10
"Arctocephalus pusillus_3_box","lower jaw","female","adult","-","transverse","dorsal",626101,11
"Arctocephalus pusillus_3_box","mandible","female","adult","right","midsagittal","interior",534070,12
"Arctocephalus pusillus_3_box","mandible","female","adult","right","midsagittal","exterior",605601,13
"Arctocephalus pusillus_3_box","pelvis","female","-","right","midsagittal","exterior",921555,14
"Arctocephalus pusillus_3_box","pelvis","female","-","right","midsagittal","interior",409438,15
"Arctocephalus pusillus_3_box","vertebrae (3)","female","-","-","midsagittal","-",618010,16
"Arctocephalus pusillus_3_box","vertebrae (3)","female","-","-","midsagittal","-",424688,17
"Arctocephalus pusillus_3_box","femur","female","-","left","transverse","ventral",583030,18
"Arctocephalus pusillus_3_box","femur","female","-","left","transverse","dorsal",142949,19
"Arctocephalus pusillus_3_box","vertebrae (lumbar,caudal)","female","-","-","coronal","anterior",301247,20
"Arctocephalus pusillus_3_box","vertebrae (lumbar,caudal)","female","-","-","coronal","posterior",824756,21
"Arctocephalus pusillus_3_box","vertebrae (lumbar,caudal)","female","-","-","midsagittal","left",408731,22
"Arctocephalus pusillus_3_box","vertebrae (lumbar,caudal)","female","-","-","midsagittal","right",503832,23
"Arctocephalus pusillus_3_box","vertebrae (lumbar,caudal)","female","-","-","transverse","ventral",234945,24
"Arctocephalus pusillus_3_box","vertebrae (thoracical, 2)","female","adult","-","sagittal","right",546769,25
"Arctocephalus pusillus_3_box","vertebrae (thoracical, 2)","female","adult","-","sagittal","left",882454,26
"Arctocephalus pusillus_3_box","atlas","female","adult","-","transverse","dorsal",725040,27
"Arctocephalus pusillus_3_box","atlas","female","adult","-","transverse","ventral",631696,28
"Arctocephalus pusillus_3_box","skull","male","-","-","transverse","dorsal",369240,29
"Arctocephalus pusillus_3_box","skull","male","-","-","transverse","ventral",771188,30
"Arctocephalus pusillus_3_box","humerus","male","adult","right","transverse","dorsal",443596,31
"Arctocephalus pusillus_3_box","humerus","male","adult","right","transverse","ventral",320793,32
"Arctocephalus pusillus_3_box","humerus","male","adult","right","coronal","anterior",539670,33
"Arctocephalus pusillus_3_box","rib","-","-","-","coronal","-",248879,34
"Arctocephalus pusillus_3_box","tibia fibula","-","-","right","midsagittal","exterior",953109,35
"Arctocephalus pusillus_3_box","tibia fibula","-","-","right","midsagittal","interior",857426,36
"Arctocephalus pusillus_3_box","humerus","male","-","right","transverse","dorsal",395808,37
"Arctocephalus pusillus_3_box","humerus","male","-","right","transverse","ventral",789527,38
"Arctocephalus pusillus_3_box","humerus","male","-","right","coronal","anterior",843797,39
"Arctocephalus pusillus_3_box","humerus","male","-","right","coronal","anterior",472356,40
"Arctocephalus pusillus_3_box","ulna","male","adult","right","transverse","dorsal",141163,41
"Arctocephalus pusillus_3_box","ulna","male","adult","right","transverse","ventral",737279,42
"Arctocephalus pusillus_3_box","femur","female","adult","left","transverse","ventral",702086,43
"Arctocephalus pusillus_3_box","femur","female","adult","left","transverse","dorsal",890648,44
"Arctocephalus pusillus_3_box","scapula","male","adult","left","transverse","dorsal",899587,45
"Arctocephalus pusillus_3_box","scapula","male","adult","left","transverse","ventral",367870,46
"Arctocephalus pusillus_3_box","femur","male","-","left","transverse","dorsal",793083,47
"Arctocephalus pusillus_3_box","femur","male","-","left","transverse","ventral",425562,48
"Arctocephalus pusillus_3_box","mandible","male","adult","right","midsagittal","exterior",557451,49
"Arctocephalus pusillus_3_box","mandible","male","adult","right","midsagittal","interior",339502,50
"Arctocephalus pusillus_3_box","baculum (2)","male","-","-","-","-",213199,51
"Arctocephalus pusillus_3_box","baculum (2)","male","-","-","-","-",385826,52
"Arctocephalus pusillus_3_box","vertebrae (cervical)","male","-","-","coronal","anterior",861822,53
"Arctocephalus pusillus_3_box","vertebrae (cervical)","male","-","-","coronal","posterior",218214,54
"Arctocephalus pusillus_3_box","vertebrae (cervical)","male","-","-","midsagittal","left",203124,55
"Arctocephalus pusillus_3_box","vertebrae (cervical)","male","-","-","midsagittal","right",855669,56
"Cystophora cristata","forelimb (complete)","-","-","left","transverse","dorsal",122111,57
"Cystophora cristata","radius","-","-","left","transverse","dorsal",785057,58
"Cystophora cristata","radius","-","-","left","transverse","ventral",826337,59
"Cystophora cristata","ulna","-","-","left","transverse","dorsal",473827,60
"Cystophora cristata","ulna","-","-","left","transverse","ventral",816336,61
"Cystophora cristata","humerus","-","-","left","transverse","dorsal",577254,62
"Cystophora cristata","humerus","-","-","left","transverse","ventral",202531,63
"Cystophora cristata","humerus","-","-","left","coronal","anterior",384622,64
"Cystophora cristata","forelimb (complete)","-","-","right","transverse","dorsal",590210,65
"Cystophora cristata","radius","-","-","right","transverse","dorsal",959465,66
"Cystophora cristata","radius","-","-","right","transverse","ventral",572953,67
"Cystophora cristata","ulna","-","-","right","transverse","dorsal",923156,68
"Cystophora cristata","ulna","-","-","right","transverse","ventral",247336,69
"Cystophora cristata","scapula","-","-","right","transverse","dorsal",332223,70
"Cystophora cristata","scapula","-","-","right","transverse","ventral",976552,71
"Cystophora cristata","humerus","-","-","right","transverse","dorsal",346942,72
"Cystophora cristata","humerus","-","-","right","transverse","ventral",991660,73
"Cystophora cristata","humerus","-","-","right","coronal","anterior",974436,74
"Halichoerus grypus_1","scapula","-","-","right","transverse","dorsal",518317,75
"Halichoerus grypus_1","scapula","-","-","right","transverse","ventral",460219,76
"Halichoerus grypus_1","scapula","-","-","left","transverse","dorsal",752411,77
"Halichoerus grypus_1","scapula","-","-","left","transverse","ventral",344432,78
"Halichoerus grypus_1","humerus","-","-","left","transverse","ventral",191371,79
"Halichoerus grypus_1","humerus","-","-","left","transverse","dorsal",289108,80
"Halichoerus grypus_1","humerus","-","-","left","coronal","anterior",898495,81
"Halichoerus grypus_1","humerus","-","-","right","transverse","dorsal",957070,82
"Halichoerus grypus_1","humerus","-","-","right","transverse","ventral",976773,83
"Halichoerus grypus_1","humerus","-","-","right","coronal","anterior",601661,84
"Halichoerus grypus_1","ulna (incomplete)","-","-","right","transverse","dorsal",279638,85
"Halichoerus grypus_1","ulna (incomplete)","-","-","right","transverse","ventral",322571,86
"Halichoerus grypus_2","ulna","-","-","left","transverse","dorsal",142583,87
"Halichoerus grypus_2","ulna","-","-","left","transverse","ventral",340720,88
"Halichoerus grypus_2","radius","-","-","right","transverse","dorsal",300807,89
"Halichoerus grypus_2","radius","-","-","right","transverse","ventral",370196,90
"Halichoerus grypus_2","humerus","-","-","-","transverse","ventral",266208,91
"Halichoerus grypus_2","humerus","-","-","-","transverse","dorsal",251830,92
"Halichoerus grypus_2","humerus","-","-","-","coronal","anterior",902845,93
"Halichoerus grypus_3","scapula","-","subadult","right","transverse","dorsal",183627,94
"Halichoerus grypus_3","scapula","-","subadult","right","transverse","ventral",260242,95
"Halichoerus grypus_3","scapula","male","adult","right","transverse","dorsal",877981,96
"Halichoerus grypus_3","scapula","male","adult","right","transverse","ventral",851712,97
"Halichoerus grypus_3","scapula","-","-","right","transverse","dorsal",428970,98
"Halichoerus grypus_3","scapula","-","-","right","transverse","ventral",801093,99
"Halichoerus grypus_3","scapula","-","adult","left","transverse","dorsal",147852,100
"Halichoerus grypus_3","scapula","-","adult","left","transverse","ventral",818385,101
"Halichoerus grypus_3","humerus","female","adult","left","transverse","ventral",362555,102
"Halichoerus grypus_3","humerus","female","adult","left","transverse","dorsal",736154,103
"Halichoerus grypus_3","humerus","female","adult","left","coronal","anterior",357849,104
"Halichoerus grypus_3","humerus","female","-","right","transverse","ventral",336685,105
"Halichoerus grypus_3","humerus","female","-","right","transverse","dorsal",314884,106
"Halichoerus grypus_3","humerus","female","-","right","coronal","anterior",859301,107
"Halichoerus grypus_4-1","scapula","male","-","right","transverse","dorsal",692352,108
"Halichoerus grypus_4-1","scapula","male","-","right","transverse","ventral",159778,109
"Halichoerus grypus_4-2","scapula","-","-","right","transverse","dorsal",702152,110
"Halichoerus grypus_4-2","scapula","-","-","right","transverse","ventral",980369,111
"Halichoerus grypus_4-3","humerus","-","-","right","transverse","ventral",581504,112
"Halichoerus grypus_4-3","humerus","-","-","right","transverse","dorsal",175267,113
"Halichoerus grypus_4-3","humerus","-","-","right","coronal","anterior",106717,114
"Halichoerus grypus_4-4","ulna (incomplete)","male","immature","left","transverse","dorsal",221587,115
"Halichoerus grypus_4-4","ulna (incomplete)","male","immature","left","transverse","ventral",808863,116
"Halichoerus grypus_4-4","ulna (incomplete)","male","immature","right","transverse","dorsal",295208,117
"Halichoerus grypus_4-4","ulna (incomplete)","male","immature","right","transverse","ventral",885372,118
"Halichoerus grypus_4-4","humerus","male","immature","right","transverse","ventral",610780,119
"Halichoerus grypus_4-4","humerus","male","immature","right","transverse","dorsal",298149,120
"Halichoerus grypus_4-4","humerus","male","immature","right","coronal","anterior",638334,121
"Halichoerus grypus_4-4","humerus","male","immature","left","transverse","ventral",912448,122
"Halichoerus grypus_4-4","humerus","male","immature","left","transverse","dorsal",321725,123
"Halichoerus grypus_4-4","humerus","male","immature","left","coronal","anterior",425249,124
"Halichoerus grypus_5","scapula","female","-","left","transverse","dorsal",253450,125
"Halichoerus grypus_5","scapula","female","-","left","transverse","ventral",882197,126
"Halichoerus grypus_5","scapula","female","-","right","transverse","dorsal",178532,127
"Halichoerus grypus_5","scapula","female","-","right","transverse","ventral",811748,128
"Halichoerus grypus_5","ulna","female","-","right","transverse","dorsal",350457,129
"Halichoerus grypus_5","ulna","female","-","right","transverse","ventral",819671,130
"Halichoerus grypus_5","ulna","female","-","left","transverse","dorsal",673660,131
"Halichoerus grypus_5","ulna","female","-","left","transverse","ventral",626907,132
"Halichoerus grypus_5","humerus","female","-","right","transverse","ventral",186673,133
"Halichoerus grypus_5","humerus","female","-","right","transverse","dorsal",446865,134
"Halichoerus grypus_5","humerus","female","-","right","coronal","anterior",218798,135
"Odobenus sp.","ulna","-","-","right","transverse","dorsal",534281,136
"Odobenus sp.","ulna","-","-","right","transverse","ventral",703698,137
"Odobenus sp.","radius","-","-","right","transverse","ventral",277467,138
"Odobenus sp.","radius","-","-","right","transverse","dorsal",456322,139
"Odobenus sp.","radius","-","-","right","transverse","dorsal",720105,140
"Odobenus sp.","radius","-","-","right","coronal","posterior",383529,141
"Phoca vitulina_1","forelimb (complete)","male","-","left","transverse","dorsal",333388,142
"Phoca vitulina_1","ulna","male","-","left","transverse","dorsal",554756,143
"Phoca vitulina_1","ulna","male","-","left","transverse","ventral",696142,144
"Phoca vitulina_1","radius","male","-","left","transverse","dorsal",586765,145
"Phoca vitulina_1","radius","male","-","left","transverse","ventral",515509,146
"Phoca vitulina_1","humerus","male","-","left","transverse","-",366425,147
"Phoca vitulina_1","humerus","male","-","left","transverse","ventral",558569,148
"Phoca vitulina_1","humerus","male","-","left","coronal","anterior",210207,149
"Phoca vitulina_1","humerus","male","-","left","coronal","posterior",751391,150
"Phoca vitulina_1","scapula","male","-","left","transverse","dorsal",823856,151
"Phoca vitulina_1","scapula","male","-","left","transverse","ventral",368653,152
"Phoca vitulina_1","forelimb (incomplete)","male","-","right","transverse","dorsal",456465,153
"Phoca vitulina_1","scapula","male","-","right","transverse","dorsal",949487,154
"Phoca vitulina_1","scapula","male","-","right","transverse","ventral",364557,155
"Phoca vitulina_1","ulna","male","-","right","transverse","dorsal",803259,156
"Phoca vitulina_1","ulna","male","-","right","transverse","ventral",969292,157
"Phoca vitulina_1","humerus","male","-","right","transverse","dorsal",475045,158
"Phoca vitulina_1","humerus","male","-","right","transverse","ventral",856642,159
"Phoca vitulina_1","humerus","male","-","right","coronal","anterior",757047,160
"Phoca vitulina_2","radius","-","juvenile","right","transverse","dorsal",349204,161
"Phoca vitulina_2","radius","-","juvenile","right","transverse","ventral",923867,162
"Phoca vitulina_3-1","scapula","-","-","right","transverse","dorsal",136418,163
"Phoca vitulina_3-1","scapula","-","-","right","transverse","ventral",194716,164
"Phoca vitulina_3-2","radius","-","-","left","transverse","dorsal",954061,165
"Phoca vitulina_3-2","radius","-","-","left","transverse","ventral",164255,166
"Phoca vitulina_3-3","ulna","-","-","right","transverse","dorsal",743190,167
"Phoca vitulina_3-3","ulna","-","-","right","transverse","ventral",521804,168
"Zalophus californianus","brain endocast","-","-","-","transverse","dorsal",452399,169
"Zalophus californianus","brain endocast","-","-","-","transverse","ventral",421815,170
"Zalophus californianus","skull","-","-","-","transverse","dorsal",200415,171
"Zalophus californianus","skull","-","-","-","transverse","ventral",273600,172
"Zalophus californianus","mandible (2)","-","-","left & right","midsagittal","exterior",564804,173
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,174
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,175
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,176
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,177
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,178
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,179
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,180
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,181
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,182
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,183
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,184
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,185
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,186
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,187
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,188
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,189
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,190
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,191
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,192
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,193
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,194
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,195
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,196
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,197
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,198
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,199
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,200
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,201
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,202
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,203
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,204
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,205
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,206
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,207
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,208
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,209
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,210
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,211
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,212
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,213
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,214
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,215
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,216
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,217
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,218
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,219
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,220
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,221
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,222
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,223
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,224
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,225
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,226
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,227
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,228
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,229
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,230
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,231
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,232
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,233
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,234
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,235
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,236
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,237
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,238
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,239
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,240
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,241
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,242
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,243
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,244
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,245
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,246
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,247
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,248
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,249
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,250
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,251
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,252
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,253
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,254
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,255
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,256
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,257
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,258
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,259
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,260
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,261
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,262
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,263
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,264
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,265
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,266
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,267
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,268
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,269
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,270
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,271
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,272
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,273
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,274
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,275
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,276
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,277
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,278
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,279
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,280
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,281
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,282
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,283
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,284
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,285
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,286
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,287
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,288
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,289
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,290
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,291
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,292
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,293
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,294
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,295
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,296
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,297
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,298
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,299
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,300
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,301
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,302
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,303
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,304
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,305
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,306
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,307
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,308
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,309
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,310
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,311
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,312
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,313
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,314
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,315
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,316
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,317
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,318
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,319
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,320
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,321
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,322
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,323
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,324
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,325
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,326
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,327
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,328
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,329
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,330
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,331
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,332
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,333
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,334
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,335
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,336
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,337
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,338
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,339
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,340
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,341
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,342
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,343
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,344
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,345
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,346
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,347
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,348
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,349
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,350
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,351
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,352
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,353
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,354
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,355
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,356
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,357
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,358
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,359
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,360
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,361
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,362
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,363
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,364
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,365
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,366
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,367
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,368
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,369
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,370
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,371
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,372
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,373
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,374
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,375
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,376
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,377
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,378
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,379
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,380
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,381
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,382
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,383
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,384
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,385
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,386
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,387
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,388
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,389
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,390
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,391
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,392
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,393
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,394
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,395
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,396
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,397
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,398
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,399
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,400
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,401
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,402
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,403
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,404
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,405
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,406
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,407
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,408
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,409
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,410
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,411
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,412
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,413
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,414
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,415
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,416
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,417
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,418
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,419
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,420
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,421
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,422
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,423
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,424
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,425
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,426
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,427
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,428
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,429
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,430
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,431
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,432
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,433
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,434
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,435
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,436
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,437
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,438
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,439
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,440
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,441
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,442
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,443
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,444
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,445
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,446
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,447
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,448
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,449
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,450
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,451
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,452
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,453
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,454
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,455
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,456
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,457
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,458
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,459
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,460
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,461
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,462
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,463
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,464
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,465
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,466
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,467
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,468
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,469
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,470
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,471
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,472
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,473
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,474
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,475
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,476
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,477
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,478
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,479
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,480
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,481
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,482
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,483
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,484
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,485
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,486
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,487
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,488
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,489
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,490
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,491
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,492
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,493
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,494
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,495
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,496
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,497
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,498
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,499
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,500
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,501
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,502
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,503
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,504
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,505
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,506
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,507
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,508
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,509
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,510
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,511
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,512
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,513
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,514
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,515
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,516
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,517
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,518
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,519
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,520
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,521
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,522
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,523
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,524
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,525
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,526
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,527
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,528
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,529
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,530
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,531
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,532
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,533
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,534
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,535
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,536
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,537
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,538
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,539
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,540
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,541
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,542
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,543
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,544
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,545
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,546
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,547
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,548
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,549
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,550
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,551
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,552
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,553
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,554
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,555
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,556
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,557
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,558
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,559
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,560
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,561
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,562
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,563
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,564
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,565
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,566
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,567
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,568
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,569
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,570
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,571
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,572
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,573
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,574
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,575
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,576
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,577
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,578
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,579
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,580
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,581
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,582
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,583
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,584
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,585
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,586
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,587
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,588
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,589
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,590
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,591
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,592
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,593
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,594
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,595
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,596
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,597
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,598
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,599
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,600
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,601
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,602
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,603
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,604
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,605
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,606
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,607
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,608
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,609
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,610
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,611
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,612
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,613
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,614
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,615
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,616
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,617
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,618
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,619
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,620
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,621
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,622
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,623
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,624
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,625
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,626
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,627
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,628
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,629
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,630
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,631
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,632
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,633
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,634
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,635
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,636
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,637
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,638
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,639
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,640
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,641
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,642
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,643
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,644
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,645
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,646
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,647
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,648
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,649
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,650
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,651
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,652
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,653
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,654
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,655
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,656
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,657
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,658
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,659
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,660
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,661
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,662
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,663
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,664
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,665
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,666
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,667
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,668
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,669
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,670
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,671
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,672
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,673
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,674
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,675
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,676
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,677
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,678
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,679
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,680
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,681
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,682
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,683
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,684
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,685
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,686
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,687
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,688
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,689
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,690
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,691
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,692
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,693
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,694
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,695
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,696
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,697
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,698
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,699
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,700
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,701
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,702
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,703
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,704
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,705
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,706
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,707
NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,708
